name: fl_resume
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_advanced_avatar: ^1.5.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  remix_icon_icons: ^1.0.1
  responsive_framework: ^1.4.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
